/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import type { GenericContractsDeclaration } from "$lib/utils/scaffold-eth/contract";

const deployedContracts = {
  11155420: {
    SHINE: {
      address: "0xb78E3E846FAf57Db15FfF17d8200a7736A7EDfBF",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "dataHash",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "storer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "nodeId",
              type: "bytes",
            },
          ],
          name: "DataHashStored",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "hashes",
              type: "bytes32[]",
            },
            {
              internalType: "bytes[]",
              name: "nodeIds",
              type: "bytes[]",
            },
          ],
          name: "batchStoreDataHashes",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "dataHashes",
          outputs: [
            {
              internalType: "bool",
              name: "exists",
              type: "bool",
            },
            {
              internalType: "address",
              name: "storer",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "nodeId",
              type: "bytes",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "dataHash",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "nodeId",
              type: "bytes",
            },
          ],
          name: "storeDataHash",
          outputs: [
            {
              internalType: "bytes",
              name: "",
              type: "bytes",
            },
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "dataHash",
              type: "bytes32",
            },
          ],
          name: "verifyDataHash",
          outputs: [
            {
              internalType: "bool",
              name: "exists",
              type: "bool",
            },
            {
              internalType: "address",
              name: "storer",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "nodeId",
              type: "bytes",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
